#!/usr/bin/env ruby
# Copyright 2011, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

loc=File.expand_path(File.dirname(__FILE__))
def usage (rc)
  puts "Usage: crowbar <area> <subcommand>"
  puts "  Areas: #{@areas.join(" ")}"
  exit rc
end

@areas = Dir.glob("./crowbar_*").map! { |x| x.gsub("./crowbar_", "") }
@areas << Dir.glob(File.join(loc,"crowbar_*")).map! { |x| x.gsub(File.join(loc,"crowbar_"), "") }
@areas = @areas.flatten

if ARGV.length == 0
  usage -1
end

area = ARGV.shift

usage -1 unless @areas.include?(area)

exec("./crowbar_#{area}", *ARGV) if File.exists?("./crowbar_#{area}")
exec(File.join(loc,"crowbar_#{area}"), *ARGV) if File.exists?(File.join(loc,"crowbar_#{area}"))
