BARCLAMP_NAME=nova
MAJOR_VERSION=0
MINOR_VERSION=8
SVN_REVISION=${SVN_REVISION:-custom}
BUILD_NUMBER=${BUILD_NUMBER:-custom}
RPM_CONTEXT_NUMBER=${SVN_REVISION}_${BUILD_NUMBER}
DEB_CONTEXT_NUMBER=${SVN_REVISION}-${BUILD_NUMBER}
