#!/bin/sh
#
# qemu-kvm networking script. Creates a private network for the VM, which can
# communicate externally via NAT through the 'kvm-nat' bridge.
#
# Crowbar contains a DHCP server and hence should always run in its own private
# network to avoid rogue DHCP answers, especially when in a company network!

BRIDGE=kvm-nat
NETWORK=192.168.124.0
HOST=192.168.124.1
MASK=255.255.255.0

echo "$0:"
echo "Setting up the network bridge for $1"
brctl addbr "$BRIDGE"
brctl addif "$BRIDGE" "$1"
ifconfig "$BRIDGE" "$HOST" netmask "$MASK"
ip link set "$1" up
ip link set "$BRIDGE" up

if iptables -t nat -L POSTROUTING -n | grep ^MASQUERADE | awk '{print $4}' | cut -d/ -f1 | grep "$NETWORK" >/dev/null
then
  echo "IP masquerading already set up"
else
  echo "Setting up IP masquerading"
  iptables -t nat -A POSTROUTING -s "$NETWORK"/"$MASK" -d ! "$NETWORK"/"$MASK" -j MASQUERADE
fi

echo "Setting up IP forwarding"
sysctl net.ipv4.ip_forward=1
