#!/bin/bash
#
# Script: install
#
# Copyright (c) 2011 Dell Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

export OS_TOKEN=centos-6.2

cd /tftpboot/redhat_dvd/extra
if screen -ls |grep -q crowbar-install; then
    echo "Crowbar install is already running."
    echo "You can attach to it with 'screen -r -S crowbar-install'"
    exit 0
fi
screen -d -m -S crowbar-install -t 'Crowbar Install' \
    script -f -c "./install-chef.sh $1" /var/log/install.log
echo "Crowbar install started under screen."
echo "You can attach to it by running:"
echo "    sudo screen -r -S crowbar-install"
echo "Once inside, pressing ctrl-a d will detach and leave the session running."
cd -
