#!/usr/bin/env ruby
# Copyright 2011, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


require File.join(File.expand_path(File.dirname(__FILE__)), "barclamp_lib")
@barclamp = "network"


@commands["allocate_ip"] = [ "allocate_ip(ARGV.shift,ARGV.shift,ARGV.shift,ARGV.shift)", "allocate_ip <name> <node> <network> <range> - Allocate an ip for a name on a network from a range" ]
@commands["enable_interface"] = [ "enable_interface(ARGV.shift,ARGV.shift,ARGV.shift)", "enable_interface <name> <node> <network> - Ensure that an interface is present for the specified network" ]

def enable_interface(name, node, network)
  usage -1 if name.nil? or name == ""
  usage -1 if node.nil? or node == ""
  usage -1 if network.nil? or network == ""

  @data = { "name" => node, "network" => network }.to_json
  struct = post_json("/enable_interface/#{name}", @data)

  if struct[1] == 200
    [ "Edited #{name} #{struct[0].inspect}", 0 ]
  elsif struct[1] == 404
    [ "Failed to edit: #{name} : Not Found", 1 ]
  elsif struct[1] == 400
    [ "Failed to edit: #{name} : Errors in data\n#{struct[0]}", 1 ]
  else
    [ "Failed to talk to service enable_interface: #{struct[1]}: #{struct[0]}", 1 ]
  end
end

def allocate_ip(name, node, network, range)
  usage -1 if name.nil? or name == ""
  usage -1 if network.nil? or network == ""
  usage -1 if node.nil? or node == ""
  usage -1 if range.nil? or range == ""

  @data = { "name" => node, "network" => network, "range" => range }.to_json
  struct = post_json("/allocate_ip/#{name}", @data)

  if struct[1] == 200
    [ "Edited #{name} #{struct[0].inspect}", 0 ]
  elsif struct[1] == 404
    [ "Failed to edit: #{name} : Not Found", 1 ]
  elsif struct[1] == 400
    [ "Failed to edit: #{name} : Errors in data\n#{struct[0]}", 1 ]
  else
    [ "Failed to talk to service allocate_ip: #{struct[1]}: #{struct[0]}", 1 ]
  end
end

main
