default[:ruby][:version] = "1.9.2-p180"
default[:ruby][:source]  = "http://ftp.ruby-lang.org//pub/ruby/1.9/ruby-#{ruby[:version]}.tar.gz"
default[:ruby][:path]    = "/cloudfoundry/deploy/rubies/ruby-#{ruby[:version]}"
default[:rubygems][:version] = "1.5.2"
default[:rubygems][:bundler][:version] = "1.0.10"

default[:deployment][:group] = "1000"
default[:deployment][:name] = "devbox"
default[:deployment][:config_path] = "/home/openstack/.cloudfoundry/devbox/config"
default[:deployment][:user] = "openstack"
default[:deployment][:home] = "/home/openstack/.cloudfoundry/devbox"
