#!/usr/bin/ruby

require 'rubygems'
require 'json'
require 'getoptlong'

#
# Parsing options can be added by adding to this list before calling opt_parse
# 
@options = [
    [ [ '--help', '-h', GetoptLong::NO_ARGUMENT ], "--help or -h - help" ],
    [ [ '--attribute', '-a', GetoptLong::REQUIRED_ARGUMENT ], "--attribute <attribute> or -a <attribute>  - Name of hash object to return.  Use . as sub-hash delimiter" ]
]

@attributes = []


def usage (rc)
  puts "Usage: parse_node_data [options] <filename>"
  @options.each do |options|
    puts "  #{options[1]}"
  end
  exit rc
end

def help
  usage 0
end


### Start MAIN ###

def opt_parse()
  sub_options = @options.map { |x| x[0] }
  lsub_options = @options.map { |x| [ x[0][0], x[2] ] }
  opts = GetoptLong.new(*sub_options)

  opts.each do |opt, arg|
    case opt
      when '--help'
        usage 0
      when '--attribute'
        @attributes << arg
      else
        usage -1
    end
  end

  if ARGV.length != 1
    usage -1
  end
end

def main()
  opt_parse
  
  hash = JSON.parse(File.open(ARGV[0]).read)

  @attributes.each do |attr|
    data = hash
    fields = attr.split(".") 
    fields.each { |x| data = data[x] unless data.nil? }

    puts "#{attr}=#{data}"
  end

end

main

