#!/bin/bash -e
#
# This script is executed at the end of appliance creation.  Here you can do
# one-time actions to modify your appliance before it is ever used, like
# removing files and directories to make it smaller, creating symlinks,
# generating indexes, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance
# (oem = disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile

# read in KIWI utility functions
. /.kconfig

#======================================
# Prune extraneous files
#--------------------------------------
baseStripLocales $kiwi_language

#======================================
# Service configuration
#--------------------------------------
chkconfig ntp on

#======================================
# Workarounds
#--------------------------------------
# Fix failing console-kit-log-system-start service
mkdir -p /var/log/ConsoleKit

exit 0