#!/bin/sh
# example backup script to be added in /etc/cron.daily/
btarballname=crowbar-$(date +%F)
# must have setup a ~/.crowbarrc containing
#[default]
#password = xxx
crowbarctl backup create $btarballname && \
echo "Created backup in /var/lib/crowbar/backup/$btarballname.tar.gz"
